const API_URL = "https://creator-autopilot-7.onrender.com";
let D = {};function nav(p){document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===p));title.textContent={home:"Overview",studio:"AI Studio",planner:"Auto Planner",calendar:"Calendar",social:"Social Accounts",settings:"Settings"}[p];({home,studio,planner,calendar,social,settings}[p])()}
function row(p){return `<div class="row"><div><b>${esc(p.title)}</b><div class="muted">${p.platform}${p.date?" · "+p.date:""}</div></div><span class="pill">${p.status}</span></div>`}
function home(){app.innerHTML=`<div class="grid"><div class="card"><span class="muted">CONTENT</span><div class="metric">${D.stats.posts}</div></div><div class="card"><span class="muted">PUBLISHED</span><div class="metric">${D.stats.published}</div></div><div class="card"><span class="muted">SCHEDULED</span><div class="metric">${D.stats.scheduled}</div></div><div class="card"><span class="muted">VIEWS</span><div class="metric">${D.stats.views.toLocaleString()}</div></div></div><div class="two"><div class="card"><h2>Content pipeline</h2><div class="list">${D.posts.length?D.posts.slice(0,8).map(row).join(""):`<p class="muted">No content yet. Open AI Studio to start.</p>`}</div></div><div class="card"><h2>Autopilot brain</h2><p class="muted">Generate ideas → scripts → captions → schedule. Real social publishing is enabled only after official OAuth/API adapters are configured.</p><button class="primary" onclick="nav('planner')">Build 7-day plan</button></div></div>`}
function studio(){app.innerHTML=`<div class="two"><div class="card"><h2>Idea generator</h2><div class="form"><input id="niche" value="${esc(D.settings.niche)}"><button class="primary" onclick="ideas()">Generate</button><div id="ideas" class="list"></div></div></div><div class="card"><h2>Script + caption</h2><div class="form"><input id="st" placeholder="Select or type a title"><button class="primary" onclick="genScript()">Generate script</button><button class="primary" onclick="genCaption()">Generate caption</button><pre id="out"></pre></div></div></div>`}
async function ideas(){let d=await api("/api/ai/ideas",{method:"POST",body:JSON.stringify({niche:niche.value})});document.querySelector("#ideas").innerHTML=d.ideas.map(x=>`<div class="row"><span>${esc(x)}</span><button onclick='useTitle(${JSON.stringify(x)})'>Use</button></div>`).join("")}function useTitle(x){st.value=x}
async function genScript(){let d=await api("/api/ai/script",{method:"POST",body:JSON.stringify({title:st.value})});out.textContent=d.hook+"\\n\\n"+d.script}
async function genCaption(){let d=await api("/api/ai/caption",{method:"POST",body:JSON.stringify({title:st.value})});out.textContent=d.caption}
function planner(){app.innerHTML=`<div class="card"><h2>Automatic content planner</h2><p class="muted">Create a multi-day plan from your niche.</p><div class="form"><input id="days" type="number" min="1" max="7" value="7"><button class="primary" onclick="makePlan()">Generate plan</button><div id="plan" class="list"></div></div></div>`}
async function makePlan(){let d=await api("/api/ai/plan",{method:"POST",body:JSON.stringify({niche:D.settings.niche,days:days.value})});plan.innerHTML=d.plan.map(p=>`<div class="row"><div><b>${esc(p.title)}</b><div class="muted">${p.date} · ${p.platform}</div></div><button onclick='addPlanned(${JSON.stringify(p)})'>Add</button></div>`).join("")}
async function addPlanned(p){await api("/api/posts",{method:"POST",body:JSON.stringify({...p,status:"Scheduled"})});await load();nav("planner")}
function calendar(){app.innerHTML=`<div class="card"><h2>Calendar</h2><div class="list">${D.posts.sort((a,b)=>(a.date||"9999").localeCompare(b.date||"9999")).map(row).join("")||"<p class=muted>Calendar is empty.</p>"}</div></div>`}
function social(){app.innerHTML=`<div class="grid">${["youtube","instagram","facebook"].map(p=>`<div class="card"><h2>${cap(p)}</h2><p class="muted">${D.connections[p]?"Connected":"Not connected"}</p><button class="primary" onclick="connect('${p}',${!D.connections[p]})">${D.connections[p]?"Disconnect":"Connect"}</button></div>`).join("")}</div>`}
async function connect(p,v){await api("/api/connections/"+p,{method:"POST",body:JSON.stringify({connected:v})});await load();nav("social")}
function settings(){app.innerHTML=`<div class="card"><h2>Workspace</h2><div class="form"><input id="bn" value="${esc(D.settings.brandName)}"><input id="nn" value="${esc(D.settings.niche)}"><input id="tz" value="${esc(D.settings.timezone)}"><input id="dp" type="number" min="1" max="10" value="${D.settings.dailyPosts}"><button class="primary" onclick="save()">Save</button></div></div>`}
async function save(){await api("/api/settings",{method:"POST",body:JSON.stringify({brandName:bn.value,niche:nn.value,timezone:tz.value,dailyPosts:Number(dp.value)})});await load();nav("settings")}
async function toggleAuto(){await api("/api/settings",{method:"POST",body:JSON.stringify({autoPilot:!D.settings.autoPilot})});await load()}
function quick(){modal.classList.remove("hidden")}function closeModal(){modal.classList.add("hidden")}async function newPost(){await api("/api/posts",{method:"POST",body:JSON.stringify({title:qt.value,platform:qp.value,date:qd.value,status:"Draft"})});closeModal();await load()}
function render(p){nav(p)}function cap(x){return x[0].toUpperCase()+x.slice(1)}function esc(x){return String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
document.querySelectorAll(".nav").forEach(x=>x.onclick=()=>nav(x.dataset.page));load().catch(e=>app.innerHTML=`<div class=card>${esc(e.message)}</div>`);
